# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anpr',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 632008))),
                ('Vehicle_Number', models.CharField(default=b'NA', max_length=200)),
                ('Lane_Number', models.IntegerField()),
                ('Flag', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Axle_Count',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 636322))),
                ('Lane_Number', models.IntegerField(default=0)),
                ('Axle', models.IntegerField(default=0)),
                ('Flag', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Edit_Lane',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Location', models.CharField(default=b'TADA', max_length=200)),
                ('Lane_Number', models.IntegerField()),
                ('User_Name', models.CharField(default=b'NA', max_length=200)),
                ('Direction', models.CharField(default=b'NA', max_length=200)),
                ('Created_Time', models.DateTimeField(auto_now_add=True)),
                ('Updated_Time', models.DateTimeField(auto_now=True)),
                ('Anpr_Ip', models.GenericIPAddressField(default=b'NA')),
                ('Camera_Ip', models.GenericIPAddressField(default=b'NA')),
                ('Profiler_Ip', models.GenericIPAddressField(default=b'NA')),
                ('Boombarrier_Ip', models.GenericIPAddressField(default=b'NA')),
                ('Weighbridge_Ip', models.GenericIPAddressField(default=b'NA')),
                ('User_Ip', models.GenericIPAddressField(default=b'NA')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Details',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Transaction_Id', models.CharField(max_length=200)),
                ('Vehicle_Number', models.CharField(max_length=200)),
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 633183))),
                ('Officer_Name', models.CharField(max_length=100)),
                ('Permit', models.DateField()),
                ('Vehicle_Type', models.CharField(default=b'NA', max_length=200)),
                ('Weight', models.IntegerField(default=0)),
                ('Lane_Number', models.IntegerField(default=0)),
                ('Location', models.CharField(default=b'TADA', max_length=200)),
                ('Comment', models.CharField(default=b'NA', max_length=100)),
                ('Vehicle_Class', models.CharField(default=b'NA', max_length=100)),
                ('Vehicle_Status', models.CharField(default=b'NA', max_length=100)),
                ('Fine_Amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Details',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Lane_1', models.IntegerField(default=0)),
                ('L1_User', models.CharField(default=b'NA', max_length=200)),
                ('L1_Login', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 638224))),
                ('Logout', models.CharField(default=b'NA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Transaction_Id', models.CharField(max_length=200)),
                ('Vehicle_Number', models.CharField(default=b'NA', max_length=200)),
                ('Dimension_Height', models.IntegerField(default=0)),
                ('Dimension_Length', models.IntegerField(default=0)),
                ('Dimension_Breadth', models.IntegerField(default=0)),
                ('Pollution', models.DateField()),
                ('Fitness', models.DateField()),
                ('Permit', models.DateField()),
                ('User_Name', models.CharField(default=b'NA', max_length=200)),
                ('Officer_Name', models.CharField(default=b'NA', max_length=200)),
                ('Axle', models.IntegerField(default=0)),
                ('Vehicle_Type', models.CharField(default=b'NA', max_length=200)),
                ('Location', models.CharField(default=b'TADA', max_length=200)),
                ('Lane_Number', models.IntegerField(default=0)),
                ('Direction', models.CharField(default=b'NA', max_length=200)),
                ('Weight', models.IntegerField(default=0)),
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 629627))),
                ('Registration_Date', models.DateField()),
                ('Chassis_Number', models.CharField(default=b'NA', max_length=200)),
                ('Engine_Number', models.CharField(default=b'NA', max_length=200)),
                ('Vehicle_Fuel_Type', models.CharField(default=b'NA', max_length=200)),
                ('Engine_Cubic_Capacity', models.CharField(default=b'NA', max_length=200)),
                ('Tax', models.DateField()),
                ('Insurance', models.DateField()),
                ('National_Permit', models.DateField()),
                ('Authorization', models.DateField()),
                ('Laden_Weight', models.IntegerField(default=0)),
                ('Unladen_Weight', models.IntegerField(default=0)),
                ('Fine_Amount', models.IntegerField(default=0)),
                ('Comment', models.CharField(default=b'NA', max_length=100)),
                ('Vehicle_Class', models.CharField(default=b'NA', max_length=100)),
                ('Sensor_Height', models.IntegerField(default=0)),
                ('Sensor_Length', models.IntegerField(default=0)),
                ('Sensor_Breadth', models.IntegerField(default=0)),
                ('Sensor_Axle', models.IntegerField(default=0)),
                ('Vehicle_Status', models.CharField(default=b'NA', max_length=100)),
                ('Image_1', models.CharField(default=b'NA', max_length=1000)),
                ('Image_2', models.CharField(default=b'NA', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Lane_Number', models.IntegerField(default=0)),
                ('Webapp', models.GenericIPAddressField(default=b'NA')),
                ('Anpr', models.GenericIPAddressField(default=b'NA')),
                ('Profiler', models.GenericIPAddressField(default=b'NA')),
                ('Weighbridge', models.GenericIPAddressField(default=b'NA')),
                ('Boombarrier', models.GenericIPAddressField(default=b'NA')),
                ('Tolluser', models.GenericIPAddressField(default=b'NA')),
                ('Overall_Health', models.GenericIPAddressField(default=b'NA')),
                ('Camera', models.GenericIPAddressField(default=b'NA')),
                ('User_Name', models.CharField(default=b'NA', max_length=100)),
                ('Location', models.CharField(default=b'TADA', max_length=100)),
                ('Direction', models.CharField(default=b'NA', max_length=100)),
                ('Status', models.IntegerField(default=0)),
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 636916))),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Vehicle_Number', models.CharField(default=0, max_length=200)),
                ('Transaction_Id', models.CharField(default=0, max_length=200)),
                ('Permit', models.DateField()),
                ('Lane_Number', models.IntegerField()),
                ('Officer_Id', models.IntegerField()),
                ('officer_Name', models.CharField(max_length=100)),
                ('Fine_Amount', models.IntegerField()),
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 632582))),
                ('User_Name', models.CharField(default=b'NA', max_length=100)),
                ('Location', models.CharField(default=b'TADA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Lane_Number', models.IntegerField(default=0)),
                ('Webapp', models.CharField(default=b'NA', max_length=200)),
                ('Anpr', models.CharField(default=b'NA', max_length=200)),
                ('Profiler', models.CharField(default=b'NA', max_length=200)),
                ('Weighbridge', models.CharField(default=b'NA', max_length=200)),
                ('Boombarrier', models.CharField(default=b'NA', max_length=200)),
                ('Tolluser', models.CharField(default=b'NA', max_length=200)),
                ('Overall_Health', models.CharField(default=b'NA', max_length=200)),
                ('Camera', models.CharField(default=b'NA', max_length=200)),
                ('User_Name', models.CharField(default=b'NA', max_length=100)),
                ('Location', models.CharField(default=b'TADA', max_length=100)),
                ('Status', models.IntegerField(default=0)),
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 637686))),
            ],
        ),
        migrations.CreateModel(
            name='Relay_Panel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Lane_1', models.BooleanField(default=1)),
                ('Lane_2', models.BooleanField(default=1)),
                ('Lane_3', models.BooleanField(default=1)),
                ('Lane_4', models.BooleanField(default=1)),
                ('Lane_5', models.BooleanField(default=1)),
                ('Lane_6', models.BooleanField(default=1)),
                ('Lane_7', models.BooleanField(default=1)),
                ('Lane_8', models.BooleanField(default=1)),
                ('Lane_9', models.BooleanField(default=1)),
                ('Lane_10', models.BooleanField(default=1)),
                ('Lane_11', models.BooleanField(default=1)),
                ('Lane_12', models.BooleanField(default=1)),
                ('Lane_13', models.BooleanField(default=1)),
                ('Lane_14', models.BooleanField(default=1)),
                ('Lane_15', models.BooleanField(default=1)),
                ('Lane_16', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Vehicle_Number', models.CharField(default=0, max_length=200)),
                ('Dimension_Length', models.IntegerField()),
                ('Dimension_Height', models.IntegerField()),
                ('Dimension_Breadth', models.IntegerField()),
                ('Fitness', models.DateField()),
                ('Permit', models.DateField()),
                ('Pollution', models.DateField()),
                ('Axle', models.IntegerField()),
                ('Vehicle_Class', models.CharField(default=b'NA', max_length=100)),
                ('Registration_Date', models.DateField()),
                ('Chassis_Number', models.CharField(default=b'NA', max_length=200)),
                ('Engine_Number', models.CharField(default=b'NA', max_length=200)),
                ('Vehicle_Fuel_Type', models.CharField(default=b'NA', max_length=200)),
                ('Engine_Cubic_Capacity', models.CharField(default=b'NA', max_length=200)),
                ('Tax', models.DateField()),
                ('Insurance', models.DateField()),
                ('National_Permit', models.DateField()),
                ('Authorization', models.DateField()),
                ('Unladen_Weight', models.IntegerField(default=0)),
                ('Vehicle_Type', models.CharField(default=b'NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Details',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Lane_Number', models.IntegerField(default=0)),
                ('Dimension_Height', models.IntegerField(default=0)),
                ('Dimension_Breadth', models.IntegerField(default=0)),
                ('Dimension_Length', models.IntegerField(default=0)),
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 633856))),
                ('Flag', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('User_Type', models.CharField(max_length=100)),
                ('Created_Time', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 630716))),
                ('Updated_Time', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 630740))),
                ('Password', models.CharField(default=b'NA', max_length=100)),
                ('User_Name', models.CharField(default=b'NA', max_length=100)),
                ('First_Name', models.CharField(default=b'NA', max_length=100)),
                ('Last_Name', models.CharField(default=b'NA', max_length=100)),
                ('Lane_Number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weigh_Bridge',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 10, 4, 635880))),
                ('Lane_Number', models.IntegerField(default=0)),
                ('Weight', models.IntegerField(default=0)),
                ('Flag', models.BooleanField(default=0)),
            ],
        ),
    ]
